extends:
  - spectral:oas

rules:
  operation-operationId: error
  operation-tags: error
  operation-description: warn
  operation-success-response: error
  oas3-api-servers: warn
  info-contact: warn
